Repository trento-project/workbench, pull requests merged in 2025-06, with the labels that each got.

#21 Plan already applied
  pkg/operator/clustermaintenancechange_v1.go
  pkg/operator/clustermaintenancechange_v1_test.go
  pkg/operator/executor.go
  pkg/operator/executor_test.go
  pkg/operator/mock_phaser.go
  pkg/operator/saptuneapplysolution_v1.go
  pkg/operator/saptuneapplysolution_v1_test.go
  pkg/operator/saptunechangesolution_v1.go
  pkg/operator/saptunechangesolution_v1_test.go
Labels: enhancement

#20 SAP instance start/stop
  pkg/operator/registry.go
  pkg/operator/sapinstancestart_v1.go
  pkg/operator/sapinstancestart_v1_test.go
  pkg/operator/sapinstancestop_v1.go
  pkg/operator/sapinstancestop_v1_test.go
Labels: enhancement

#24 Enable pacemaker systemd unit operator
  .mockery.yaml
  go.mod
  go.sum
  internal/systemd/dbus.go
  internal/systemd/mocks/mock_DbusConnector.go
  internal/systemd/mocks/mock_Systemd.go
  internal/systemd/mocks/mock_SystemdLoader.go
  internal/systemd/systemd.go
  internal/systemd/systemd_test.go
  pkg/operator/base.go
  pkg/operator/executor.go
  pkg/operator/executor_test.go
  pkg/operator/mock_phaser.go
  pkg/operator/registry.go
  pkg/operator/serviceenable_v1.go
  pkg/operator/serviceenable_v1_test.go
Labels: enhancement

#28 Replace initial delay by checking empty processes list
  pkg/operator/sapinstancestart_v1.go
  pkg/operator/sapinstancestart_v1_test.go
Labels: bug

#29 Fix systemd relater test name
  internal/systemd/systemd_test.go
Labels: chore
